// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("LANGIDMappingsConsole")>]
[<assembly: AssemblyProductAttribute("LANGIDMappings")>]
[<assembly: AssemblyDescriptionAttribute("Mappings between Windows LANGIDs and other standards")>]
[<assembly: AssemblyVersionAttribute("0.2.0")>]
[<assembly: AssemblyFileVersionAttribute("0.2.0")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "LANGIDMappingsConsole"
    let [<Literal>] AssemblyProduct = "LANGIDMappings"
    let [<Literal>] AssemblyDescription = "Mappings between Windows LANGIDs and other standards"
    let [<Literal>] AssemblyVersion = "0.2.0"
    let [<Literal>] AssemblyFileVersion = "0.2.0"
    let [<Literal>] AssemblyConfiguration = "Release"
