// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("LANGIDMappings")>]
[<assembly: AssemblyProductAttribute("LANGIDMappings")>]
[<assembly: AssemblyDescriptionAttribute("Mappings between Windows LANGIDs and other standards")>]
[<assembly: AssemblyVersionAttribute("0.1")>]
[<assembly: AssemblyFileVersionAttribute("0.1")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "LANGIDMappings"
    let [<Literal>] AssemblyProduct = "LANGIDMappings"
    let [<Literal>] AssemblyDescription = "Mappings between Windows LANGIDs and other standards"
    let [<Literal>] AssemblyVersion = "0.1"
    let [<Literal>] AssemblyFileVersion = "0.1"
