// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("LANGIDMappings")>]
[<assembly: AssemblyProductAttribute("LANGIDMappings")>]
[<assembly: AssemblyVersionAttribute("0.4.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2021-05-26T00:00:00.0000000-07:00")>]
[<assembly: AssemblyFileVersionAttribute("0.4.0")>]
[<assembly: AssemblyInformationalVersionAttribute("0.4.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","release")>]
[<assembly: AssemblyMetadataAttribute("GitHash","175644b95e7224c418baad985281e93b88c16c81")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "LANGIDMappings"
    let [<Literal>] AssemblyProduct = "LANGIDMappings"
    let [<Literal>] AssemblyVersion = "0.4.0"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2021-05-26T00:00:00.0000000-07:00"
    let [<Literal>] AssemblyFileVersion = "0.4.0"
    let [<Literal>] AssemblyInformationalVersion = "0.4.0"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "release"
    let [<Literal>] AssemblyMetadata_GitHash = "175644b95e7224c418baad985281e93b88c16c81"
